version: '2.3'

volumes:
  e2etests_modules: null

services:
  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
    ports:
    - "4040:4040"
    - "5050:5050"
    volumes:
    - ./allure-results:/app/allure-results